### ISSUE TITLE
February 8, 2018 HTML/Flexbox CSS/AngularJS homework

### ISSUE THREAD

**Issue by johnlenonmaghanoy** [honghueit/StudyAngularJS#6]
These assignment will test whether you can apply the concepts of the previous lessons on a different user interface.

Note:
Do not push codes that doesn't follow proper coding style( whether HTML, CSS or Javascript )
After you complete these homework, kindly push it to the repository and publish it online using surge, once your homework is already published online, kindly send me the link of your homework so that I can check it, okay?

1st mockup:

![itemdiscountmanager](https://user-images.githubusercontent.com/9315686/35974018-77d39462-0d12-11e8-8f34-15a7363e5324.png)

2nd mockup:

![itempricemanager](https://user-images.githubusercontent.com/9315686/35974066-9c82e45c-0d12-11e8-9ef2-75676de7a4e2.png)

**Comment by honghueit** [comment]
i dont understand why have 2 mockup? is it mean i have to do 2 test with 2 mockup?
